#pragma once
#include "../Tbl.h"

namespace Tbl
{
    struct Quest2
    {
        uint32_t ID;
        uint32_t localizedTextIdTitle;
        uint32_t localizedTextIdText;
        uint32_t flags;
        uint32_t conLevel;
        uint32_t type;
        uint32_t preq_level;
        uint32_t preq_flags;
        uint32_t preq_quest0;
        uint32_t preq_quest01;
        uint32_t preq_quest02;
        uint32_t preq_race;
        uint32_t preq_item;
        uint32_t questPlayerFactionEnum;
        uint32_t worldZoneId;
        uint32_t localizedTextIdCompletionOverride;
        uint32_t reward_xpOverride;
        uint32_t reward_cashOverride;
        uint32_t pushed_itemId0;
        uint32_t pushed_itemId01;
        uint32_t pushed_itemId02;
        uint32_t pushed_itemId03;
        uint32_t pushed_itemId04;
        uint32_t pushed_itemId05;
        uint32_t pushed_itemCount0;
        uint32_t pushed_itemCount01;
        uint32_t pushed_itemCount02;
        uint32_t pushed_itemCount03;
        uint32_t pushed_itemCount04;
        uint32_t pushed_itemCount05;
        uint32_t objective0;
        uint32_t objective01;
        uint32_t objective02;
        uint32_t objective03;
        uint32_t objective04;
        uint32_t objective05;
        uint32_t localizedTextIdGiverTextUnknown;
        uint32_t localizedTextIdGiverTextAccepted;
        uint32_t localizedTextIdReceiverTextAccepted;
        uint32_t localizedTextIdReceiverTextAchieved;
        uint32_t localizedTextIdGiverSayAccepted;
        uint32_t localizedTextIdReceiverSayCompleted;
        uint32_t preq_class;
        uint32_t groupId;
        uint32_t factionIdPreq0;
        uint32_t factionIdPreq01;
        uint32_t factionIdPreq02;
        uint32_t factionLevelPreq0;
        uint32_t factionLevelPreq01;
        uint32_t factionLevelPreq02;
        uint32_t factionLevelCompPreq0;
        uint32_t factionLevelCompPreq01;
        uint32_t factionLevelCompPreq02;
        uint32_t questIdExclusionPreq0;
        uint32_t questIdExclusionPreq1;
        uint32_t questIdExclusionPreq2;
        uint32_t localizedTextIdAcceptResponse;
        uint32_t localizedTextIdCompleteResponse;
        uint32_t WorldLocation2IdReceiver;
        uint32_t worldLocation2IdAltReceiver00;
        uint32_t worldLocation2IdAltReceiver01;
        uint32_t worldLocation2IdAltReceiver02;
        uint32_t prerequisiteIdAltReceiver00;
        uint32_t prerequisiteIdAltReceiver01;
        uint32_t prerequisiteIdAltReceiver02;
        uint32_t questDirectionIdAltReceiver00;
        uint32_t questDirectionIdAltReceiver01;
        uint32_t questDirectionIdAltReceiver02;
        uint32_t localizedTextIdCompletedSummary;
        uint32_t localizedTextIdGiverIncompleteResponse;
        uint32_t localizedTextIdReceiverIncompleteResponse;
        uint32_t quest2DifficultyId;
        uint32_t maxTimeAllowedMS;
        uint32_t prerequisiteId;
        uint32_t questShareEnum;
        uint32_t subMissionPathType;
        uint32_t localizedTextIdCompletedObjectiveShort;
        uint32_t quest2SubTypeId;
        uint32_t localizedTextIdMoreInfoSay00;
        uint32_t localizedTextIdMoreInfoSay01;
        uint32_t localizedTextIdMoreInfoSay02;
        uint32_t localizedTextIdMoreInfoSay03;
        uint32_t localizedTextIdMoreInfoSay04;
        uint32_t localizedTextIdMoreInfoText00;
        uint32_t localizedTextIdMoreInfoText01;
        uint32_t localizedTextIdMoreInfoText02;
        uint32_t localizedTextIdMoreInfoText03;
        uint32_t localizedTextIdMoreInfoText04;
        uint32_t virtualItemIdPushed00;
        uint32_t virtualItemIdPushed01;
        uint32_t virtualItemIdPushed02;
        uint32_t virtualItemIdPushed03;
        uint32_t virtualItemPushedCount00;
        uint32_t virtualItemPushedCount01;
        uint32_t virtualItemPushedCount02;
        uint32_t virtualItemPushedCount03;
        uint32_t virtualItemPushedObjectiveFlagsEnum00;
        uint32_t virtualItemPushedObjectiveFlagsEnum01;
        uint32_t virtualItemPushedObjectiveFlagsEnum02;
        uint32_t virtualItemPushedObjectiveFlagsEnum03;
        uint32_t questDirectionIdCompletion;
        uint32_t faction2IdRewardReputation00;
        uint32_t faction2IdRewardReputation01;
        float rewardReputationOverride00;
        float rewardReputationOverride01;
        uint32_t questCategoryId;
        uint32_t localizedTextIdGiverSayDecline;
        uint32_t periodicQuestGroupId;
        uint32_t periodicQuestWeight;
        uint32_t questRepeatPeriodEnum;
        uint32_t questContentFinderTypeEnum;
        uint32_t groupSize;

        uint32_t GetID() const { return ID; }

        void Read(const File& f, uint32_t row)
        {
            size_t i = 0;
            ID = f.getUint(row, i++);
            localizedTextIdTitle = f.getUint(row, i++);
            localizedTextIdText = f.getUint(row, i++);
            flags = f.getUint(row, i++);
            conLevel = f.getUint(row, i++);
            type = f.getUint(row, i++);
            preq_level = f.getUint(row, i++);
            preq_flags = f.getUint(row, i++);
            preq_quest0 = f.getUint(row, i++);
            preq_quest01 = f.getUint(row, i++);
            preq_quest02 = f.getUint(row, i++);
            preq_race = f.getUint(row, i++);
            preq_item = f.getUint(row, i++);
            questPlayerFactionEnum = f.getUint(row, i++);
            worldZoneId = f.getUint(row, i++);
            localizedTextIdCompletionOverride = f.getUint(row, i++);
            reward_xpOverride = f.getUint(row, i++);
            reward_cashOverride = f.getUint(row, i++);
            pushed_itemId0 = f.getUint(row, i++);
            pushed_itemId01 = f.getUint(row, i++);
            pushed_itemId02 = f.getUint(row, i++);
            pushed_itemId03 = f.getUint(row, i++);
            pushed_itemId04 = f.getUint(row, i++);
            pushed_itemId05 = f.getUint(row, i++);
            pushed_itemCount0 = f.getUint(row, i++);
            pushed_itemCount01 = f.getUint(row, i++);
            pushed_itemCount02 = f.getUint(row, i++);
            pushed_itemCount03 = f.getUint(row, i++);
            pushed_itemCount04 = f.getUint(row, i++);
            pushed_itemCount05 = f.getUint(row, i++);
            objective0 = f.getUint(row, i++);
            objective01 = f.getUint(row, i++);
            objective02 = f.getUint(row, i++);
            objective03 = f.getUint(row, i++);
            objective04 = f.getUint(row, i++);
            objective05 = f.getUint(row, i++);
            localizedTextIdGiverTextUnknown = f.getUint(row, i++);
            localizedTextIdGiverTextAccepted = f.getUint(row, i++);
            localizedTextIdReceiverTextAccepted = f.getUint(row, i++);
            localizedTextIdReceiverTextAchieved = f.getUint(row, i++);
            localizedTextIdGiverSayAccepted = f.getUint(row, i++);
            localizedTextIdReceiverSayCompleted = f.getUint(row, i++);
            preq_class = f.getUint(row, i++);
            groupId = f.getUint(row, i++);
            factionIdPreq0 = f.getUint(row, i++);
            factionIdPreq01 = f.getUint(row, i++);
            factionIdPreq02 = f.getUint(row, i++);
            factionLevelPreq0 = f.getUint(row, i++);
            factionLevelPreq01 = f.getUint(row, i++);
            factionLevelPreq02 = f.getUint(row, i++);
            factionLevelCompPreq0 = f.getUint(row, i++);
            factionLevelCompPreq01 = f.getUint(row, i++);
            factionLevelCompPreq02 = f.getUint(row, i++);
            questIdExclusionPreq0 = f.getUint(row, i++);
            questIdExclusionPreq1 = f.getUint(row, i++);
            questIdExclusionPreq2 = f.getUint(row, i++);
            localizedTextIdAcceptResponse = f.getUint(row, i++);
            localizedTextIdCompleteResponse = f.getUint(row, i++);
            WorldLocation2IdReceiver = f.getUint(row, i++);
            worldLocation2IdAltReceiver00 = f.getUint(row, i++);
            worldLocation2IdAltReceiver01 = f.getUint(row, i++);
            worldLocation2IdAltReceiver02 = f.getUint(row, i++);
            prerequisiteIdAltReceiver00 = f.getUint(row, i++);
            prerequisiteIdAltReceiver01 = f.getUint(row, i++);
            prerequisiteIdAltReceiver02 = f.getUint(row, i++);
            questDirectionIdAltReceiver00 = f.getUint(row, i++);
            questDirectionIdAltReceiver01 = f.getUint(row, i++);
            questDirectionIdAltReceiver02 = f.getUint(row, i++);
            localizedTextIdCompletedSummary = f.getUint(row, i++);
            localizedTextIdGiverIncompleteResponse = f.getUint(row, i++);
            localizedTextIdReceiverIncompleteResponse = f.getUint(row, i++);
            quest2DifficultyId = f.getUint(row, i++);
            maxTimeAllowedMS = f.getUint(row, i++);
            prerequisiteId = f.getUint(row, i++);
            questShareEnum = f.getUint(row, i++);
            subMissionPathType = f.getUint(row, i++);
            localizedTextIdCompletedObjectiveShort = f.getUint(row, i++);
            quest2SubTypeId = f.getUint(row, i++);
            localizedTextIdMoreInfoSay00 = f.getUint(row, i++);
            localizedTextIdMoreInfoSay01 = f.getUint(row, i++);
            localizedTextIdMoreInfoSay02 = f.getUint(row, i++);
            localizedTextIdMoreInfoSay03 = f.getUint(row, i++);
            localizedTextIdMoreInfoSay04 = f.getUint(row, i++);
            localizedTextIdMoreInfoText00 = f.getUint(row, i++);
            localizedTextIdMoreInfoText01 = f.getUint(row, i++);
            localizedTextIdMoreInfoText02 = f.getUint(row, i++);
            localizedTextIdMoreInfoText03 = f.getUint(row, i++);
            localizedTextIdMoreInfoText04 = f.getUint(row, i++);
            virtualItemIdPushed00 = f.getUint(row, i++);
            virtualItemIdPushed01 = f.getUint(row, i++);
            virtualItemIdPushed02 = f.getUint(row, i++);
            virtualItemIdPushed03 = f.getUint(row, i++);
            virtualItemPushedCount00 = f.getUint(row, i++);
            virtualItemPushedCount01 = f.getUint(row, i++);
            virtualItemPushedCount02 = f.getUint(row, i++);
            virtualItemPushedCount03 = f.getUint(row, i++);
            virtualItemPushedObjectiveFlagsEnum00 = f.getUint(row, i++);
            virtualItemPushedObjectiveFlagsEnum01 = f.getUint(row, i++);
            virtualItemPushedObjectiveFlagsEnum02 = f.getUint(row, i++);
            virtualItemPushedObjectiveFlagsEnum03 = f.getUint(row, i++);
            questDirectionIdCompletion = f.getUint(row, i++);
            faction2IdRewardReputation00 = f.getUint(row, i++);
            faction2IdRewardReputation01 = f.getUint(row, i++);
            rewardReputationOverride00 = f.getFloat(row, i++);
            rewardReputationOverride01 = f.getFloat(row, i++);
            questCategoryId = f.getUint(row, i++);
            localizedTextIdGiverSayDecline = f.getUint(row, i++);
            periodicQuestGroupId = f.getUint(row, i++);
            periodicQuestWeight = f.getUint(row, i++);
            questRepeatPeriodEnum = f.getUint(row, i++);
            questContentFinderTypeEnum = f.getUint(row, i++);
            groupSize = f.getUint(row, i++);
        }
    };
}
