#pragma once
#include "../Tbl.h"

namespace Tbl
{
    struct ReplaceableMaterialInfo
    {
        uint32_t ID;
        uint32_t type;
        uint32_t flags;
        uint32_t op;
        uint32_t blend;
        uint32_t shaderNum00;
        uint32_t shaderNum01;
        uint32_t numLayers;
        uint32_t colorIndex01;
        uint32_t colorIndex00;
        uint32_t colorIndex02;
        uint32_t colorIndex03;
        uint32_t normalIndex00;
        uint32_t normalIndex01;
        uint32_t normalIndex02;
        uint32_t normalIndex03;
        uint32_t heightSource00;
        uint32_t heightSource01;
        uint32_t heightSource02;
        uint32_t heightSource03;
        uint32_t opacitySource00;
        uint32_t opacitySource01;
        uint32_t opacitySource02;
        uint32_t opacitySource03;
        uint32_t glossSource00;
        uint32_t glossSource01;
        uint32_t glossSource02;
        uint32_t glossSource03;
        uint32_t glowSource00;
        uint32_t glowSource01;
        uint32_t glowSource02;
        uint32_t glowSource03;
        uint32_t shaderSource00;
        uint32_t shaderSource01;
        uint32_t shaderSource02;
        uint32_t shaderSource03;
        float heightValue00;
        float heightValue01;
        float heightValue02;
        float heightValue03;
        float opacityValue00;
        float opacityValue01;
        float opacityValue02;
        float opacityValue03;
        float glossValue00;
        float glossValue01;
        float glossValue02;
        float glossValue03;
        float glowValue00;
        float glowValue01;
        float glowValue02;
        float glowValue03;
        float shaderValue00;
        float shaderValue01;
        float shaderValue02;
        float shaderValue03;
        float heightScale00;
        float heightScale01;
        float heightScale02;
        float heightScale03;
        float heightOffset00;
        float heightOffset01;
        float heightOffset02;
        float heightOffset03;
        float parallaxScale00;
        float parallaxScale01;
        float parallaxScale02;
        float parallaxScale03;
        float parallaxOffset00;
        float parallaxOffset01;
        float parallaxOffset02;
        float parallaxOffset03;
        uint32_t textureTiles00;
        uint32_t textureTiles01;
        uint32_t textureTiles02;
        uint32_t textureTiles03;
        float colorModX00;
        float colorModX01;
        float colorModX02;
        float colorModX03;
        float colorModY00;
        float colorModY01;
        float colorModY02;
        float colorModY03;
        float colorModZ00;
        float colorModZ01;
        float colorModZ02;
        float colorModZ03;
        uint32_t materialTypeId00;
        uint32_t materialTypeId01;
        uint32_t materialTypeId02;
        uint32_t materialTypeId03;
        std::wstring colorTexture00;
        std::wstring colorTexture01;
        std::wstring colorTexture02;
        std::wstring colorTexture03;
        std::wstring normalTexture00;
        std::wstring normalTexture01;
        std::wstring normalTexture02;
        std::wstring normalTexture03;

        uint32_t GetID() const { return ID; }

        void Read(const File& f, uint32_t row)
        {
            size_t i = 0;
            ID = f.getUint(row, i++);
            type = f.getUint(row, i++);
            flags = f.getUint(row, i++);
            op = f.getUint(row, i++);
            blend = f.getUint(row, i++);
            shaderNum00 = f.getUint(row, i++);
            shaderNum01 = f.getUint(row, i++);
            numLayers = f.getUint(row, i++);
            colorIndex01 = f.getUint(row, i++);
            colorIndex00 = f.getUint(row, i++);
            colorIndex02 = f.getUint(row, i++);
            colorIndex03 = f.getUint(row, i++);
            normalIndex00 = f.getUint(row, i++);
            normalIndex01 = f.getUint(row, i++);
            normalIndex02 = f.getUint(row, i++);
            normalIndex03 = f.getUint(row, i++);
            heightSource00 = f.getUint(row, i++);
            heightSource01 = f.getUint(row, i++);
            heightSource02 = f.getUint(row, i++);
            heightSource03 = f.getUint(row, i++);
            opacitySource00 = f.getUint(row, i++);
            opacitySource01 = f.getUint(row, i++);
            opacitySource02 = f.getUint(row, i++);
            opacitySource03 = f.getUint(row, i++);
            glossSource00 = f.getUint(row, i++);
            glossSource01 = f.getUint(row, i++);
            glossSource02 = f.getUint(row, i++);
            glossSource03 = f.getUint(row, i++);
            glowSource00 = f.getUint(row, i++);
            glowSource01 = f.getUint(row, i++);
            glowSource02 = f.getUint(row, i++);
            glowSource03 = f.getUint(row, i++);
            shaderSource00 = f.getUint(row, i++);
            shaderSource01 = f.getUint(row, i++);
            shaderSource02 = f.getUint(row, i++);
            shaderSource03 = f.getUint(row, i++);
            heightValue00 = f.getFloat(row, i++);
            heightValue01 = f.getFloat(row, i++);
            heightValue02 = f.getFloat(row, i++);
            heightValue03 = f.getFloat(row, i++);
            opacityValue00 = f.getFloat(row, i++);
            opacityValue01 = f.getFloat(row, i++);
            opacityValue02 = f.getFloat(row, i++);
            opacityValue03 = f.getFloat(row, i++);
            glossValue00 = f.getFloat(row, i++);
            glossValue01 = f.getFloat(row, i++);
            glossValue02 = f.getFloat(row, i++);
            glossValue03 = f.getFloat(row, i++);
            glowValue00 = f.getFloat(row, i++);
            glowValue01 = f.getFloat(row, i++);
            glowValue02 = f.getFloat(row, i++);
            glowValue03 = f.getFloat(row, i++);
            shaderValue00 = f.getFloat(row, i++);
            shaderValue01 = f.getFloat(row, i++);
            shaderValue02 = f.getFloat(row, i++);
            shaderValue03 = f.getFloat(row, i++);
            heightScale00 = f.getFloat(row, i++);
            heightScale01 = f.getFloat(row, i++);
            heightScale02 = f.getFloat(row, i++);
            heightScale03 = f.getFloat(row, i++);
            heightOffset00 = f.getFloat(row, i++);
            heightOffset01 = f.getFloat(row, i++);
            heightOffset02 = f.getFloat(row, i++);
            heightOffset03 = f.getFloat(row, i++);
            parallaxScale00 = f.getFloat(row, i++);
            parallaxScale01 = f.getFloat(row, i++);
            parallaxScale02 = f.getFloat(row, i++);
            parallaxScale03 = f.getFloat(row, i++);
            parallaxOffset00 = f.getFloat(row, i++);
            parallaxOffset01 = f.getFloat(row, i++);
            parallaxOffset02 = f.getFloat(row, i++);
            parallaxOffset03 = f.getFloat(row, i++);
            textureTiles00 = f.getUint(row, i++);
            textureTiles01 = f.getUint(row, i++);
            textureTiles02 = f.getUint(row, i++);
            textureTiles03 = f.getUint(row, i++);
            colorModX00 = f.getFloat(row, i++);
            colorModX01 = f.getFloat(row, i++);
            colorModX02 = f.getFloat(row, i++);
            colorModX03 = f.getFloat(row, i++);
            colorModY00 = f.getFloat(row, i++);
            colorModY01 = f.getFloat(row, i++);
            colorModY02 = f.getFloat(row, i++);
            colorModY03 = f.getFloat(row, i++);
            colorModZ00 = f.getFloat(row, i++);
            colorModZ01 = f.getFloat(row, i++);
            colorModZ02 = f.getFloat(row, i++);
            colorModZ03 = f.getFloat(row, i++);
            materialTypeId00 = f.getUint(row, i++);
            materialTypeId01 = f.getUint(row, i++);
            materialTypeId02 = f.getUint(row, i++);
            materialTypeId03 = f.getUint(row, i++);
            colorTexture00 = f.getString(row, i++);
            colorTexture01 = f.getString(row, i++);
            colorTexture02 = f.getString(row, i++);
            colorTexture03 = f.getString(row, i++);
            normalTexture00 = f.getString(row, i++);
            normalTexture01 = f.getString(row, i++);
            normalTexture02 = f.getString(row, i++);
            normalTexture03 = f.getString(row, i++);
        }
    };
}
