#pragma once
#include "../Tbl.h"

namespace Tbl
{
    struct Spell4
    {
        uint32_t ID;
        std::wstring description;
        uint32_t spell4BaseIdBaseSpell;
        uint32_t tierIndex;
        uint32_t ravelInstanceId;
        uint32_t castTime;
        uint32_t spellDuration;
        uint32_t spellCoolDown;
        float targetMinRange;
        float targetMaxRange;
        float targetVerticalRange;
        uint32_t casterInnateRequirement0;
        uint32_t casterInnateRequirement1;
        uint32_t casterInnateRequirementValue0;
        uint32_t casterInnateRequirementValue1;
        uint32_t casterInnateRequirementEval0;
        uint32_t casterInnateRequirementEval1;
        uint32_t targetBeginInnateRequirement;
        uint32_t targetBeginInnateRequirementValue;
        uint32_t targetBeginInnateRequirementEval;
        uint32_t innateCostType0;
        uint32_t innateCostType1;
        uint32_t innateCost0;
        uint32_t innateCost1;
        uint32_t innateCostEMMId0;
        uint32_t innateCostEMMId1;
        uint32_t channelInitialDelay;
        uint32_t channelMaxTime;
        uint32_t channelPulseTime;
        uint32_t localizedTextIdActionBarTooltip;
        uint32_t stackPriority;
        uint32_t spell4VisualGroupId;
        uint32_t spell4IdCastEvent00;
        uint32_t spell4IdCastEvent01;
        uint32_t spell4IdCastEvent02;
        uint32_t spell4IdCastEvent03;
        uint32_t spell4ReagentId00;
        uint32_t spell4ReagentId01;
        uint32_t spell4ReagentId02;
        uint32_t spell4RunnerId00;
        uint32_t spell4RunnerId01;
        uint32_t runnerTargetTypeEnum00;
        uint32_t runnerTargetTypeEnum01;
        uint32_t prerequisiteIdRunner00;
        uint32_t prerequisiteIdRunner01;
        uint32_t abilityChargeCount;
        uint32_t abilityRechargeTime;
        uint32_t abilityRechargeCount;
        uint32_t thresholdTime;
        uint32_t abilityPointCost;
        uint32_t trainingCost;
        uint32_t spellChannelFlags;
        uint32_t ignoreFollowTimeMs;
        uint32_t spell4IdMechanicAlternateSpell;
        uint32_t spell4IdPetSwitch;
        uint32_t spell4TagId00;
        uint32_t spell4TagId01;
        uint32_t spell4TagId02;
        uint32_t spell4TagId03;
        uint32_t spell4TagId04;
        uint32_t localizedTextIdCasterIconSpellText;
        uint32_t localizedTextIdPrimaryTargetIconSpellText;
        uint32_t localizedTextIdSecondaryTargetIconSpellText;
        uint32_t localizedTextIdLASTier;
        uint32_t localizedTextIdTooltipCastInfo;
        uint32_t localizedTextIdTooltipCostInfo;
        uint32_t tooltipCastTime;
        uint32_t spell4AoeTargetConstraintsId;
        uint32_t spell4ConditionsIdCaster;
        uint32_t spell4ConditionsIdTarget;
        uint32_t spell4CCConditionsIdCaster;
        uint32_t spell4CCConditionsIdTarget;
        uint32_t spellCoolDownIdGlobal;
        uint32_t spellCoolDownId00;
        uint32_t spellCoolDownId01;
        uint32_t spellCoolDownId02;
        uint32_t spell4GroupListId;
        uint32_t missileSpeed;
        uint32_t minMissileSpeed;
        uint32_t spell4ClientMissileId00;
        uint32_t spell4ClientMissileId01;
        uint32_t spell4ClientMissileId02;
        uint32_t spell4ClientMissileId03;
        uint32_t spell4ClientMissileId04;
        uint32_t spell4ClientMissileId05;
        uint32_t globalCooldownEnum;
        uint32_t propertyFlags;
        uint32_t uiFlags;
        uint32_t spell4StackGroupId;
        uint32_t prerequisiteIdCasterCast;
        uint32_t prerequisiteIdTargetCast;
        uint32_t prerequisiteIdCasterPersistence;
        uint32_t prerequisiteIdTargetPersistence;
        uint32_t castEventConditionEnum00;
        uint32_t castEventConditionEnum01;
        uint32_t castEventConditionEnum02;
        uint32_t castEventConditionEnum03;
        uint32_t castEventTargetFlags00;
        uint32_t castEventTargetFlags01;
        uint32_t castEventTargetFlags02;
        uint32_t castEventTargetFlags03;
        uint32_t spellCastStealthChange;
        uint32_t prerequisiteIdAoeTarget;
        uint32_t prerequisiteIdAoePreferredTarget;

        uint32_t GetID() const { return ID; }

        void Read(const File& f, uint32_t row)
        {
            size_t i = 0;
            ID = f.getUint(row, i++);
            description = f.getString(row, i++);
            spell4BaseIdBaseSpell = f.getUint(row, i++);
            tierIndex = f.getUint(row, i++);
            ravelInstanceId = f.getUint(row, i++);
            castTime = f.getUint(row, i++);
            spellDuration = f.getUint(row, i++);
            spellCoolDown = f.getUint(row, i++);
            targetMinRange = f.getFloat(row, i++);
            targetMaxRange = f.getFloat(row, i++);
            targetVerticalRange = f.getFloat(row, i++);
            casterInnateRequirement0 = f.getUint(row, i++);
            casterInnateRequirement1 = f.getUint(row, i++);
            casterInnateRequirementValue0 = f.getUint(row, i++);
            casterInnateRequirementValue1 = f.getUint(row, i++);
            casterInnateRequirementEval0 = f.getUint(row, i++);
            casterInnateRequirementEval1 = f.getUint(row, i++);
            targetBeginInnateRequirement = f.getUint(row, i++);
            targetBeginInnateRequirementValue = f.getUint(row, i++);
            targetBeginInnateRequirementEval = f.getUint(row, i++);
            innateCostType0 = f.getUint(row, i++);
            innateCostType1 = f.getUint(row, i++);
            innateCost0 = f.getUint(row, i++);
            innateCost1 = f.getUint(row, i++);
            innateCostEMMId0 = f.getUint(row, i++);
            innateCostEMMId1 = f.getUint(row, i++);
            channelInitialDelay = f.getUint(row, i++);
            channelMaxTime = f.getUint(row, i++);
            channelPulseTime = f.getUint(row, i++);
            localizedTextIdActionBarTooltip = f.getUint(row, i++);
            stackPriority = f.getUint(row, i++);
            spell4VisualGroupId = f.getUint(row, i++);
            spell4IdCastEvent00 = f.getUint(row, i++);
            spell4IdCastEvent01 = f.getUint(row, i++);
            spell4IdCastEvent02 = f.getUint(row, i++);
            spell4IdCastEvent03 = f.getUint(row, i++);
            spell4ReagentId00 = f.getUint(row, i++);
            spell4ReagentId01 = f.getUint(row, i++);
            spell4ReagentId02 = f.getUint(row, i++);
            spell4RunnerId00 = f.getUint(row, i++);
            spell4RunnerId01 = f.getUint(row, i++);
            runnerTargetTypeEnum00 = f.getUint(row, i++);
            runnerTargetTypeEnum01 = f.getUint(row, i++);
            prerequisiteIdRunner00 = f.getUint(row, i++);
            prerequisiteIdRunner01 = f.getUint(row, i++);
            abilityChargeCount = f.getUint(row, i++);
            abilityRechargeTime = f.getUint(row, i++);
            abilityRechargeCount = f.getUint(row, i++);
            thresholdTime = f.getUint(row, i++);
            abilityPointCost = f.getUint(row, i++);
            trainingCost = f.getUint(row, i++);
            spellChannelFlags = f.getUint(row, i++);
            ignoreFollowTimeMs = f.getUint(row, i++);
            spell4IdMechanicAlternateSpell = f.getUint(row, i++);
            spell4IdPetSwitch = f.getUint(row, i++);
            spell4TagId00 = f.getUint(row, i++);
            spell4TagId01 = f.getUint(row, i++);
            spell4TagId02 = f.getUint(row, i++);
            spell4TagId03 = f.getUint(row, i++);
            spell4TagId04 = f.getUint(row, i++);
            localizedTextIdCasterIconSpellText = f.getUint(row, i++);
            localizedTextIdPrimaryTargetIconSpellText = f.getUint(row, i++);
            localizedTextIdSecondaryTargetIconSpellText = f.getUint(row, i++);
            localizedTextIdLASTier = f.getUint(row, i++);
            localizedTextIdTooltipCastInfo = f.getUint(row, i++);
            localizedTextIdTooltipCostInfo = f.getUint(row, i++);
            tooltipCastTime = f.getUint(row, i++);
            spell4AoeTargetConstraintsId = f.getUint(row, i++);
            spell4ConditionsIdCaster = f.getUint(row, i++);
            spell4ConditionsIdTarget = f.getUint(row, i++);
            spell4CCConditionsIdCaster = f.getUint(row, i++);
            spell4CCConditionsIdTarget = f.getUint(row, i++);
            spellCoolDownIdGlobal = f.getUint(row, i++);
            spellCoolDownId00 = f.getUint(row, i++);
            spellCoolDownId01 = f.getUint(row, i++);
            spellCoolDownId02 = f.getUint(row, i++);
            spell4GroupListId = f.getUint(row, i++);
            missileSpeed = f.getUint(row, i++);
            minMissileSpeed = f.getUint(row, i++);
            spell4ClientMissileId00 = f.getUint(row, i++);
            spell4ClientMissileId01 = f.getUint(row, i++);
            spell4ClientMissileId02 = f.getUint(row, i++);
            spell4ClientMissileId03 = f.getUint(row, i++);
            spell4ClientMissileId04 = f.getUint(row, i++);
            spell4ClientMissileId05 = f.getUint(row, i++);
            globalCooldownEnum = f.getUint(row, i++);
            propertyFlags = f.getUint(row, i++);
            uiFlags = f.getUint(row, i++);
            spell4StackGroupId = f.getUint(row, i++);
            prerequisiteIdCasterCast = f.getUint(row, i++);
            prerequisiteIdTargetCast = f.getUint(row, i++);
            prerequisiteIdCasterPersistence = f.getUint(row, i++);
            prerequisiteIdTargetPersistence = f.getUint(row, i++);
            castEventConditionEnum00 = f.getUint(row, i++);
            castEventConditionEnum01 = f.getUint(row, i++);
            castEventConditionEnum02 = f.getUint(row, i++);
            castEventConditionEnum03 = f.getUint(row, i++);
            castEventTargetFlags00 = f.getUint(row, i++);
            castEventTargetFlags01 = f.getUint(row, i++);
            castEventTargetFlags02 = f.getUint(row, i++);
            castEventTargetFlags03 = f.getUint(row, i++);
            spellCastStealthChange = f.getUint(row, i++);
            prerequisiteIdAoeTarget = f.getUint(row, i++);
            prerequisiteIdAoePreferredTarget = f.getUint(row, i++);
        }
    };
}
